/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MetzgereiRouteImport } from './routes/metzgerei'
import { Route as GasthausRouteImport } from './routes/gasthaus'
import { Route as IndexRouteImport } from './routes/index'

const MetzgereiRoute = MetzgereiRouteImport.update({
  id: '/metzgerei',
  path: '/metzgerei',
  getParentRoute: () => rootRouteImport,
} as any)
const GasthausRoute = GasthausRouteImport.update({
  id: '/gasthaus',
  path: '/gasthaus',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gasthaus': typeof GasthausRoute
  '/metzgerei': typeof MetzgereiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gasthaus': typeof GasthausRoute
  '/metzgerei': typeof MetzgereiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gasthaus': typeof GasthausRoute
  '/metzgerei': typeof MetzgereiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gasthaus' | '/metzgerei'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gasthaus' | '/metzgerei'
  id: '__root__' | '/' | '/gasthaus' | '/metzgerei'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GasthausRoute: typeof GasthausRoute
  MetzgereiRoute: typeof MetzgereiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/metzgerei': {
      id: '/metzgerei'
      path: '/metzgerei'
      fullPath: '/metzgerei'
      preLoaderRoute: typeof MetzgereiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gasthaus': {
      id: '/gasthaus'
      path: '/gasthaus'
      fullPath: '/gasthaus'
      preLoaderRoute: typeof GasthausRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GasthausRoute: GasthausRoute,
  MetzgereiRoute: MetzgereiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
