/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MetzgereiRouteImport } from './routes/metzgerei'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as GasthausRouteImport } from './routes/gasthaus'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as IndexRouteImport } from './routes/index'

const MetzgereiRoute = MetzgereiRouteImport.update({
  id: '/metzgerei',
  path: '/metzgerei',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const GasthausRoute = GasthausRouteImport.update({
  id: '/gasthaus',
  path: '/gasthaus',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/gasthaus': typeof GasthausRoute
  '/impressum': typeof ImpressumRoute
  '/metzgerei': typeof MetzgereiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/gasthaus': typeof GasthausRoute
  '/impressum': typeof ImpressumRoute
  '/metzgerei': typeof MetzgereiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/gasthaus': typeof GasthausRoute
  '/impressum': typeof ImpressumRoute
  '/metzgerei': typeof MetzgereiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/datenschutz' | '/gasthaus' | '/impressum' | '/metzgerei'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/datenschutz' | '/gasthaus' | '/impressum' | '/metzgerei'
  id:
    | '__root__'
    | '/'
    | '/datenschutz'
    | '/gasthaus'
    | '/impressum'
    | '/metzgerei'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatenschutzRoute: typeof DatenschutzRoute
  GasthausRoute: typeof GasthausRoute
  ImpressumRoute: typeof ImpressumRoute
  MetzgereiRoute: typeof MetzgereiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/metzgerei': {
      id: '/metzgerei'
      path: '/metzgerei'
      fullPath: '/metzgerei'
      preLoaderRoute: typeof MetzgereiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gasthaus': {
      id: '/gasthaus'
      path: '/gasthaus'
      fullPath: '/gasthaus'
      preLoaderRoute: typeof GasthausRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatenschutzRoute: DatenschutzRoute,
  GasthausRoute: GasthausRoute,
  ImpressumRoute: ImpressumRoute,
  MetzgereiRoute: MetzgereiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
